import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Provider } from '@/context';
import { AuthContext } from '@/context/AuthContext';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// components
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <AuthContext>
            <Navbar />
            <main className='flex min-h-screen flex-col mt-[80px]'>
              {children}
            </main>
            <ToastContainer
              position='top-right'
              autoClose={4000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme='light'
              rtl={false}
            />
          </AuthContext>
        </Provider>
      </body>
    </html>
  );
}
